language: python
python:
    - 3.5
sudo: false

cache:
  - pip: true
  - directories:
    - node_modules

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - nvm install node
    - nvm use node
    - node --version
    - npm --version
    - pip install -U pip wheel codecov
    - make requirements
script:
    - make static
    - make validate
after_success:
    - codecov
